//Add your Fluent APIs here and in other now.ts files under src/fluent
import '@servicenow/sdk/global'
import { BusinessRule, ClientScript, DateColumn, StringColumn, Table } from '@servicenow/sdk/core'
import { showStateUpdate } from '../server/script.js'

//creates todo table, with three columns (deadline, status and task)
export const x_snc_toolboxdemo_todotable = Table({
    name: 'x_snc_toolboxdemo_todotable',
    schema: {
        deadline: DateColumn({ label: 'Deadline' }),
        state: StringColumn({
            label: 'State',
            choices: {
                ready: { label: 'Ready' },
                completed: { label: 'Completed' },
                inProgress: { label: 'In Progress' },
            },
            dropdown: 'dropdown_with_none',
        }),
        task: StringColumn({ label: 'Task', maxLength: 120 }),
    },
    actions: ['read', 'update', 'create'],
    allowClientScripts: true,
    allowNewFields: true,
    allowUiActions: true,
    allowWebServiceAccess: true,
    label: 'Toolboxdemo Todotable',
})

//creates a client script that pops up 'Table loaded successfully!!' message everytime todo record is loaded
ClientScript({
    $id: Now.ID['cs0'],
    name: 'my_client_script',
    table: 'x_snc_toolboxdemo_todotable',
    active: true,
    appliesExtended: false,
    global: true,
    uiType: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolateScript: false,
    type: 'onLoad',
    script: script` function onLoad(){
        g_form.addInfoMessage("Table loaded successfully");
    }`,
})

//creates a business rule that pops up state change message whenever a todo record is updated
BusinessRule({
    $id: Now.ID['br0'],
    action: ['update', 'delete'],
    table: 'x_snc_toolboxdemo_todotable',
    script: showStateUpdate,
    name: 'LogStateChange',
    order: 100,
    when: 'after',
    active: true,
})
